# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{calendar_helper}
  s.version = "0.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Geoffrey Grosenbach"]
  s.date = %q{2010-11-30}
  s.description = %q{A simple method to create an HTML calendar for a single month. Can be styled with CSS. Usable with Ruby on Rails.}
  s.email = %q{boss AT topfunky.com}
  s.extra_rdoc_files = [
    "README.txt"
  ]
  s.files = [
    "History.txt",
    "MIT-LICENSE",
    "Manifest.txt",
    "README.txt",
    "Rakefile",
    "about.yml",
    "generators/calendar_styles/calendar_styles_generator.rb",
    "generators/calendar_styles/templates/blue/style.css",
    "generators/calendar_styles/templates/grey/style.css",
    "generators/calendar_styles/templates/red/style.css",
    "init.rb",
    "lib/calendar_helper.rb",
    "test/test_calendar_helper.rb"
  ]
  s.homepage = %q{http://rubyforge.org/projects/seattlerb}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Makes it easier to create atom feeds through Builder.}
  s.test_files = [
    "test/test_calendar_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

